### ISSUE TITLE
Create ExecuteMsg for removing a pool from the pool factory

### ISSUE THREAD

**Issue by kerber0x** [White-Whale-Defi-Platform/migaloo-core#38]
## Use case

Pools are added to the pool directory once they are created by the factory, but there is no way to delete them. Contracts will live forever on the blockchain, but if for some reason a pool is broken in any way, for example if they are instantiated wrong (wrong assets)  it could be handy to be able to remove it from the directory to keep things clean.

## Proposal

Create and implement `ExecuteMsg::RemovePair { pair_address: String }` on the `terraswap_factory` contract.

**Comment by janfabian** [comment]
@kerber0x I opened the PR, not sure if it fulfills the requirements though. Let me know :+1:
