### ISSUE TITLE
Change bigint deprecated dependency for uint

### ISSUE THREAD

**Issue by kerber0x** [White-Whale-Defi-Platform/migaloo-core#62]
https://crates.io/crates/bigint -> deprecated, replaced by -> https://crates.io/crates/uint

**Comment by janfabian** [comment]
@kerber0x Hi, I wanted to start on this, but I'm struggling with the usage of the bigint. It seems to me as nested dependency of the `cosmwasm-bignumber`. Is this task about pull request to the `cosmwasm-bignumber` and then upgrade it back here?

**Comment by kerber0x** [comment]
Hello @janfabian! I haven't looked at it in details but it is possible you are right. There could be that cosmwasm-bignumber is itself deprecated and now replaced by something else. Otherwise I think what you described is the the way to go :+1:

**Comment by janfabian** [comment]
two observation so far - 
- the repository https://github.com/terra-money/terra-cosmwasm seems abandon to me
- there are Uint256 and Decimal256 in `cosmwasm_std` https://docs.rs/cosmwasm-std/latest/cosmwasm_std/struct.Uint256.html

I'd propose to switch to the `cosmwasm_std` which uses `uint` lib

**Comment by kerber0x** [comment]
@janfabian I am addressing this issue fyi
