### ISSUE TITLE
Collect fees for vault factory not working

### ISSUE THREAD

**Issue by kerber0x** [White-Whale-Defi-Platform/migaloo-core#63]
The following query is not working:

```json 
{
  "collect_fees":{
    "collect_fees_for":{
      "factory":{
        "factory_addr":"address",
        "factory_type":{
          "vault":{}
        }
      }
    }
  }
}
```

Error: Query failed with (18): failed to execute message; message index: 0: Generic error: Querier contract error: codespace: wasm, code: 9: execute wasm contract failed: invalid request

P.S.: You can still collect the fees for a vault by using `CollectFeesFor::Contracts` and providing the vault.

**Comment by janfabian** [comment]
@kerber0x I did test run of this query https://finder.terra.money/testnet/tx/93093c66ca6cb6c91d107e22da76b3e7b2fc83095edc00553a06136ee6d997f6 and it ran. Also swap factory works https://finder.terra.money/testnet/tx/5DCCC060DF24F7E3393340408BD4732159CCD1EF64B509ECDE2BDC1FDBC78FF7

Based on the generic error response I'd suspect that the address `factory_addr` was not pointing to actual vault factory maybe ?

**Comment by kaimen-sano** [comment]
Yes, that was the error - bad deployment rather than anything wrong in the code. Thank you for investigating
